package codigo;

public enum Tokens {
    Inicio_Programa,
    Fin_Programa,
    Palabra_Clase,
    Palabra_Funcion,
    Tipo_Entero,
    Tipo_Decimal,
    Tipo_Cadena,
    Tipo_Booleano,
    Palabra_Si,
    Palabra_Sino_Si,
    Palabra_Sino,
    Palabra_Devolver,
    Operador_Relacional,
    Igual,
    Operador_Suma,
    Operador_Resta,
    Operador_Multiplicacion,
    Operador_Division,
    Parentesis_Apertura,
    Parentesis_Cierre,
    Llave_Apertura,
    Llave_Cierre,
    Coma,
    PuntoYComa,
    Identificador,
    Numero,
    Cadena,
    ERROR
}
